import { prisma } from "./prisma";
import type { Akta, Dokumen, PihakAkta, TandaTanganDigital } from "./types";

type StoredDocs = { dokumen: Dokumen[]; fotoTtdKlien: Dokumen[]; fotoTtdNotaris: Dokumen[]; minuta: Dokumen[]; tandaTanganDigital: TandaTanganDigital[] };
const parse = <T>(v:string|null|undefined,f:T):T => { try{return v?JSON.parse(v) as T:f;}catch{return f;} };
const toDate=(v?:string|null)=>{const d=v?new Date(v):new Date();return Number.isNaN(d.getTime())?new Date():d;};
function readDocs(v:string|null|undefined):StoredDocs { const parsed:any=parse<any>(v,[]); if(Array.isArray(parsed)) return {dokumen:parsed,fotoTtdKlien:[],fotoTtdNotaris:[],minuta:[],tandaTanganDigital:[]}; return {dokumen:Array.isArray(parsed?.dokumen)?parsed.dokumen:[],fotoTtdKlien:Array.isArray(parsed?.fotoTtdKlien)?parsed.fotoTtdKlien:[],fotoTtdNotaris:Array.isArray(parsed?.fotoTtdNotaris)?parsed.fotoTtdNotaris:[],minuta:Array.isArray(parsed?.minuta)?parsed.minuta:[],tandaTanganDigital:Array.isArray(parsed?.tandaTanganDigital)?parsed.tandaTanganDigital:[]}; }
function fromDb(x:any):Akta { const pihak=parse<PihakAkta[]>(x.pihakJson,[]); const docs=readDocs(x.dokumenJson); return {id:x.id,nomorAkta:x.nomorAkta,tanggal:new Date(x.tanggal).toISOString().slice(0,10),kategori:x.kategori==='PPAT'?'PPAT':'NOTARIS',jenisAkta:x.jenisAkta,namaNotaris:x.namaNotaris,pihak,namaPihak:x.namaPihak||pihak.map(p=>p.nama).filter(Boolean).join('; '),nik:x.nik||pihak.map(p=>p.nik).filter(Boolean).join('; '),npwp:x.npwp||pihak.map(p=>p.npwp).filter(Boolean).join('; '),alamat:x.alamat||'',nomorSertifikat:x.nomorSertifikat||'',jenisHak:x.jenisHak||'',luasTanah:x.luasTanah==null?'':String(x.luasTanah),nilaiTransaksi:Number(x.nilaiTransaksi||0),nopPbb:x.nopPbb||'',njop:Number(x.njop||0),tanggalSsp:x.tanggalSsp?new Date(x.tanggalSsp).toISOString().slice(0,10):'',sspPph:Number(x.sspPph||0),tanggalBphtb:x.tanggalBphtb?new Date(x.tanggalBphtb).toISOString().slice(0,10):'',bphtb:Number(x.bphtb||0),honorarium:Number(x.honorarium||0),status:x.status||'Draft',catatan:x.catatan||'',detail:parse<Record<string,string>>(x.detailJson,{}),...docs}; }
export async function listAkta():Promise<Akta[]>{return (await prisma.akta.findMany({orderBy:{createdAt:'desc'}})).map(fromDb);}
export async function getAkta(id:string){const x=await prisma.akta.findUnique({where:{id}});return x?fromDb(x):undefined;}
export async function upsertAkta(a:Akta){const dokumenJson=JSON.stringify({dokumen:a.dokumen||[],fotoTtdKlien:a.fotoTtdKlien||[],fotoTtdNotaris:a.fotoTtdNotaris||[],minuta:a.minuta||[],tandaTanganDigital:a.tandaTanganDigital||[]}); const data:any={nomorAkta:a.nomorAkta,tanggal:toDate(a.tanggal),kategori:a.kategori,jenisAkta:a.jenisAkta,namaNotaris:a.namaNotaris,namaPihak:a.namaPihak,nik:a.nik||null,npwp:a.npwp||null,alamat:a.alamat||null,nomorSertifikat:a.nomorSertifikat||null,jenisHak:a.jenisHak||null,luasTanah:a.luasTanah?Number(a.luasTanah):null,nilaiTransaksi:Number(a.nilaiTransaksi||0),nopPbb:a.nopPbb||null,njop:Number(a.njop||0),tanggalSsp:a.tanggalSsp?toDate(a.tanggalSsp):null,sspPph:Number(a.sspPph||0),tanggalBphtb:a.tanggalBphtb?toDate(a.tanggalBphtb):null,bphtb:Number(a.bphtb||0),honorarium:Number(a.honorarium||0),status:a.status||'Draft',catatan:a.catatan||null,detailJson:JSON.stringify(a.detail||{}),pihakJson:JSON.stringify(a.pihak||[]),dokumenJson}; return prisma.akta.upsert({where:{id:a.id},create:{id:a.id,...data},update:data});}
export async function saveAkta(data:Akta[]){const existing=await prisma.akta.findMany({select:{id:true}});const wanted=new Set(data.map(x=>x.id));const remove=existing.filter(x=>!wanted.has(x.id)).map(x=>x.id);if(remove.length)await prisma.akta.deleteMany({where:{id:{in:remove}}});for(const a of data)await upsertAkta(a);}
