import { NextResponse } from 'next/server';
import { randomUUID } from 'crypto';
import { getAkta, listAkta, upsertAkta } from '@/lib/store';
import { prisma } from '@/lib/prisma';
import type { Akta, PihakAkta, TandaTanganDigital } from '@/lib/types';

const num=(v:unknown)=>Number(v||0), str=(v:unknown)=>String(v||'');
const cleanDokumen=(v:unknown)=>Array.isArray(v)?v.filter((x:any)=>x&&x.url):[];
const cleanPihak=(v:unknown):PihakAkta[]=>Array.isArray(v)?v.slice(0,6).map((x:any)=>({nama:str(x?.nama).trim(),nik:str(x?.nik).replace(/\D/g,'').slice(0,16),npwp:str(x?.npwp).trim(),scanIdentitas:cleanDokumen(x?.scanIdentitas)})).filter(x=>x.nama||x.nik||x.npwp||x.scanIdentitas.length):[];
const cleanTtd=(v:unknown):TandaTanganDigital[]=>Array.isArray(v)?v.filter((x:any)=>x&&x.dataUrl).map((x:any)=>({nama:str(x.nama),peran:str(x.peran),dataUrl:str(x.dataUrl),tanggal:str(x.tanggal)})):[];
function normalize(b:any,id?:string):Akta{const pihak=cleanPihak(b.pihak);const fallback=pihak.length?pihak:[{nama:str(b.namaPihak),nik:str(b.nik),npwp:str(b.npwp),scanIdentitas:[]}].filter(x=>x.nama||x.nik||x.npwp);return {id:id||randomUUID(),nomorAkta:str(b.nomorAkta),tanggal:str(b.tanggal),kategori:b.kategori==='PPAT'?'PPAT':'NOTARIS',jenisAkta:str(b.jenisAkta),namaNotaris:str(b.namaNotaris),pihak:fallback,namaPihak:fallback.map(x=>x.nama).filter(Boolean).join('; '),nik:fallback.map(x=>x.nik).filter(Boolean).join('; '),npwp:fallback.map(x=>x.npwp).filter(Boolean).join('; '),alamat:str(b.alamat),nomorSertifikat:str(b.nomorSertifikat),jenisHak:str(b.jenisHak),luasTanah:str(b.luasTanah),nilaiTransaksi:num(b.nilaiTransaksi),nopPbb:str(b.nopPbb),njop:num(b.njop),tanggalSsp:str(b.tanggalSsp),sspPph:num(b.sspPph),tanggalBphtb:str(b.tanggalBphtb),bphtb:num(b.bphtb),honorarium:num(b.honorarium),status:b.status||'Draft',catatan:str(b.catatan),detail:typeof b.detail==='object'&&b.detail?b.detail:{},dokumen:cleanDokumen(b.dokumen),fotoTtdKlien:cleanDokumen(b.fotoTtdKlien),fotoTtdNotaris:cleanDokumen(b.fotoTtdNotaris),minuta:cleanDokumen(b.minuta),tandaTanganDigital:cleanTtd(b.tandaTanganDigital)};}
export async function GET(){try{return NextResponse.json(await listAkta())}catch(e){console.error(e);return NextResponse.json({error:'Gagal mengambil data akta.'},{status:500})}}
export async function POST(req:Request){try{const a=normalize(await req.json());if(!a.nomorAkta.trim())return NextResponse.json({error:'Nomor akta wajib diisi.'},{status:400});if(!a.namaNotaris.trim())return NextResponse.json({error:'Nama Notaris / PPAT wajib diisi.'},{status:400});if(!a.pihak.length||!a.pihak[0].nama.trim())return NextResponse.json({error:'Minimal nama pihak pertama wajib diisi.'},{status:400});await upsertAkta(a);return NextResponse.json({ok:true,id:a.id},{status:201})}catch(e){console.error('POST AKTA',e);return NextResponse.json({error:e instanceof Error?e.message:'Gagal menyimpan akta.'},{status:500})}}
export async function PUT(req:Request){try{const id=new URL(req.url).searchParams.get('id');if(!id)return NextResponse.json({error:'ID wajib.'},{status:400});if(!(await getAkta(id)))return NextResponse.json({error:'Data akta tidak ditemukan.'},{status:404});const a=normalize(await req.json(),id);if(!a.nomorAkta.trim())return NextResponse.json({error:'Nomor akta wajib diisi.'},{status:400});if(!a.namaNotaris.trim())return NextResponse.json({error:'Nama Notaris / PPAT wajib diisi.'},{status:400});if(!a.pihak.length||!a.pihak[0].nama.trim())return NextResponse.json({error:'Minimal nama pihak pertama wajib diisi.'},{status:400});await upsertAkta(a);return NextResponse.json({ok:true,id})}catch(e){console.error('PUT AKTA',e);return NextResponse.json({error:e instanceof Error?e.message:'Gagal memperbarui akta.'},{status:500})}}
export async function DELETE(req:Request){try{const id=new URL(req.url).searchParams.get('id');if(!id)return NextResponse.json({error:'ID wajib.'},{status:400});await prisma.akta.delete({where:{id}});return NextResponse.json({ok:true})}catch(e){console.error('DELETE AKTA',e);return NextResponse.json({error:e instanceof Error?e.message:'Gagal menghapus akta.'},{status:500})}}
